### ISSUE TITLE
Gimbal 3 support

### ISSUE THREAD

**Issue by koga73** [urbanairship/cordova-gimbal-bridge#5]
Looking at the android-gimbal-adapter there seem to be updates that this plugin needs. Specifically we are getting the following error in production with Android 8:

`
java.lang.RuntimeException: Unable to start receiver com.urbanairship.cordova.gimbal.AirshipReadyReceiver: android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3397)
   at android.app.ActivityThread.-wrap18(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
   at android.os.Handler.dispatchMessage(Handler.java:105)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6938)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
   at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:119)
   at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:108)
   at com.gimbal.internal.receiver.GimbalBroadcastReceiver.a(SourceFile:57)
   at com.gimbal.internal.receiver.GimbalBroadcastReceiver.c(SourceFile:28)
   at com.gimbal.internal.b.a(SourceFile:2305)
   at com.gimbal.internal.d.a(SourceFile:14)
   at com.gimbal.internal.d.a(SourceFile:21)
   at com.gimbal.android.Gimbal.setApiKey(SourceFile:19)
   at com.urbanairship.cordova.gimbal.GimbalPlugin.initGimbal(GimbalPlugin.java:76)
   at com.urbanairship.cordova.gimbal.AirshipReadyReceiver.onReceive(AirshipReadyReceiver.java:18)
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
   at android.app.ActivityThread.-wrap18(Unknown Source:0) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780) 
   at android.os.Handler.dispatchMessage(Handler.java:105) 
   at android.os.Looper.loop(Looper.java:164) 
   at android.app.ActivityThread.main(ActivityThread.java:6938) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
`

**Comment by rlepinski** [comment]
You need to update the plugin to latest. It should pull the latest from https://github.com/urbanairship/cordova-gimbal-sdk/blob/master/src/android/gimbal.gradle that defines gimbal v3

**Comment by rlepinski** [comment]
Oh I see, we need to update gimbal to 3.1.1 to fix that particular error

**Comment by BrianBatchelder** [comment]
@koga73 : This issue was fixed in [release 2.0.1](https://github.com/urbanairship/cordova-gimbal-bridge/releases/tag/2.0.1).

**Comment by tonymckendry** [comment]
@BrianBatchelder - I am trying to install the plugin v2.0.1 and am receiving a cordova error because the latest version in the cordova registry is 2.0.0 - do you plan to update this? 

https://www.npmjs.com/package/urbanairship-gimbal-bridge-cordova

**Comment by rlepinski** [comment]
@tonymckendry i just published it. let me know if it works for you
